server:
  port: 8082
  servlet:
    context-path: /notification
spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/bs_notification_service?authSource=admin
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      groupId: notification-group
      autoOffsetReset: earliest
      keyDeserializer: org.apache.kafka.common.serialization.StringDeserializer
      valueDeserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
notification:
  email:
    brevo-url: https://api.brevo.com
    brevo-api-key: "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"
    sender-name: "Nguyễn Quốc Huy"
    sender-email: "nguyenquochuy16092003@gmail.com"