server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  datasource:
    url: "jdbc:mysql://localhost:3306/bs_identity_service"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: root
    password: anhiuemlove33
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
jwt:
  signer-key: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  issuer: "nguyenquochuy16092003"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds

admin:
  secret-username: "admin"
  secret-password: "anhiuemlove33"

app:
  services:
    profile: http://localhost:8081/profile