server:
  port: 8888

app:
  apiPrefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity-service
          uri: http://localhost:8080
          predicates:
            - Path=${app.apiPrefix}/identity/**
          filters:
            - StripPrefix=2
        - id: profile-service
          uri: http://localhost:8081
          predicates:
            - Path=${app.apiPrefix}/profile/users/**
          filters:
            - StripPrefix=2
        - id: notification-service
          uri: http://localhost:8082
          predicates:
            - Path=${app.apiPrefix}/notification/**
          filters:
            - StripPrefix=2