server:
  port: 8084
  servlet:
    context-path: /file
spring:
  application:
    name: file-service
  data:
    mongodb:
      uri: mongodb://root:anhiuemlove33@localhost:27017/file_service?authSource=admin
  servlet:
    multipart:
      maxFileSize: 5MB
      maxRequestSize: 5MB
app:
  file:
    storageDir: C:/upload
    downloadPrefix: http://localhost:8888/api/v1/file/media/download/