server:
  port: 8085
  servlet:
    context-path: /chat
websocket:
  port: 8099
spring:
  application:
    name: chat-service
  data:
    mongodb:
      uri: mongodb://root:anhiuemlove33@localhost:27017/chat_service?authSource=admin
      auto-index-creation: true
app:
  services:
    profile:
      url: http://localhost:8081/profile